### ISSUE TITLE
bug(config/config.js): BIGBLUEBOT_BOTS is capped to 10

### ISSUE THREAD

**Issue by mschwrdtnr** [mconf/bigbluebot#23]
Hello guys,

**Problem:**
I was wondering why only 10 bots join the meeting even if I use a higher number for `BIGBLUEBOT_BOTS=`.
The maximum number of bots who can join is capped to 10 in [config/config.js](https://github.com/mconf/bigbluebot/blob/master/config/config.json#L47). 

If I enter a higher number e.g. 100 at this line the used number of the env  `BIGBLUEBOT_BOTS` is working. 

**Solution:**
Don't set a max number in config.
I don't know if it's possible to don't set this number or even use e.g. 200. Because probably this will be the maximum for a bbb meeting.

If you have suggestions I can also make a PR for this 😄 

Thanks for you work on this project!!
Cheers, Max

**Comment by pedrobmarin** [comment]
Hi @mschwrdtnr ,

The 10 cap is because of https://github.com/mconf/bigbluebot/blob/1df33cba27c101131cfa7344a88ec1f675bdfb03/config/config.json#L43-L49
The pool population is the number of browser processes and the max size represents the max number of tabs it will open for each process. All of these because, at my early tests on the bots, I found out headless Chromium had some issues while trying to use fake medias under only one browser process. This was back to 2018 I guess and may not even be a thing anymore.
So, if you want to run over 10 bots, you can just work those numbers out. The pool population can be set as an environment variable https://github.com/mconf/bigbluebot/blob/1df33cba27c101131cfa7344a88ec1f675bdfb03/.env.template#L29 if that makes any easier in your setup.

About putting 200 bots in a meeting you will soon find out a BigBlueButton client is quite heavy even in a headless browser. I was able to feed a meeting with more than that but dividing the bots in multiple machines.

**Comment by pedrobmarin** [comment]
(just realized you got almost everything right at your description of the problem, sorry!)

But, for now, I stand that changing the pool size is healthier than changing the max tabs each process can take it.

**Comment by mschwrdtnr** [comment]
Thanks for your answer and explanation. So probably it would be could if you can provide an info in the readme for people who are wondering why only 10 bots are spawning. ..maybe this issue can also be enough.

I am using your implementation in https://github.com/mconf/mconf-live-test/ and will test around with the pool_size.

**Comment by pedrobmarin** [comment]
https://github.com/mconf/bigbluebot/commit/1a6edc3a5c2e5dbe36c6d03ebb943390e2cfdb5d done!

**Comment by mschwrdtnr** [comment]
Very cool, thanks for you work!
